### ISSUE TITLE
invlid request

### ISSUE THREAD

**Issue by ekhtiari** [matteofabbri/ServerSideAnalytics#1]
hi. i see your website and i want to use it in my project. i tested your nuget and i see something.
my website created by donet core and i don't have any url that ended by .aspx 
but when i try to navigate some fake url that contain aspx i see your function insert one more record in db 
and how can i filter these invalid requests ? 
![capture](https://user-images.githubusercontent.com/10780594/42672313-8d52b408-867a-11e8-8268-fc07860b29b5.JPG)

**Comment by matteofabbri** [comment]
To remove .aspx you can use ExcludeExtension(".aspx") but probably you mean that you want to filter out every not successful request.

Nice catch, It wasn't possible because the stat was saved before the execution of the business logic so even using .Exclude( context => context.Response.StatusCode != 200 ) would not work.
But trying to fulfill your request I discovered that is possible to save the stat even after the end of execution 👍  this is great feature, thanks a lot.
I just updated the package It will be visible in minutes.

I also added some shortcut method
.ExcludeStatusCodes(404) //to filter out every status code we don't wont to track 

.LimitToStatusCodes(200) //a shorter version that will keep trace only of specified status codes 

Thanks again 🥇
